<%--  emxParameterAbortTransaction.inc   -

   Copyright (c) 1992-2012 Dassault Systemes.
   All Rights Reserved.
   This program contains proprietary and trade secret information of MatrixOne,
   Inc.  Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program.
--%>
<%@ page import="com.matrixone.apps.domain.util.*" %>

<%
  // Abort the transaction
  ContextUtil.abortTransaction(context);
%>
