<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:com:dassault_systemes:webservice" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:com:dassault_systemes:webservice" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<types>
 <xs:schema targetNamespace="urn:com:dassault_systemes:webservice:messages">
  <xs:import namespace="urn:com:dassault_systemes:webservice" schemaLocation="../xsd/IChangePasswordService.xsd"/>
 </xs:schema>
</types>
<message name="changePasswordInput">
 <part element="tns:changePassword" name="parameters"/>
</message>
<message name="changePasswordOutput">
 <part element="tns:changePasswordResponse" name="parameters"/>
</message>
<message name="changePasswordErrorType">
 <part element="tns:changePasswordErrorType" name="details"/>
</message>
<portType name="IChangePasswordService">
 <documentation>Interface for managing users Password</documentation>
 <operation name="changePassword">
  <documentation>Change a users password</documentation>
  <input message="tns:changePasswordInput"/>
  <output message="tns:changePasswordOutput"/>
  <fault message="tns:changePasswordErrorType" name="changePasswordErrorType"/>
 </operation>
</portType>
<binding name="IChangePasswordServiceBinding" type="tns:IChangePasswordService">
 <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="changePassword">
  <soap:operation soapAction="" style="document"/>
  <input>
   <soap:body use="literal"/>
  </input>
  <output>
   <soap:body use="literal"/>
  </output>
  <fault name="changePasswordErrorType">
   <soap:fault name="changePasswordErrorType" use="literal"/>
  </fault>
 </operation>
</binding>
 <service name="ChangePasswordService">
  <port binding="tns:IChangePasswordServiceBinding" name="ChangePasswordServicePort">
   <soap:address location="http://localhost:9080/rooturi/ChangePasswordService"/>
  </port>
 </service>
</definitions>
