<%--  emxNavigatorNoDocTypeInclude.inc

   Copyright (c) 1992-2020 Dassault Systemes.
   All Rights Reserved.
   This program contains proprietary and trade secret information of MatrixOne,
   Inc.  Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program

   static const char RCSID[] = $Id:  $
--%>

<%@ page import = "matrix.db.*, matrix.util.*,
				   com.matrixone.util.*,
				   com.matrixone.servlet.*,
				   com.matrixone.apps.framework.ui.*,
				   com.matrixone.apps.domain.util.*, 
				   com.matrixone.apps.domain.*, 
				   java.util.*, 
				   java.io.*, 
				   com.matrixone.jsystem.util.*"
				   errorPage="../common/emxNavigatorErrorPage.jsp"%>
				   
<%@include file = "emxNavigatorComponentSideDoorInclude.inc"%>
<%@include file = "../emxContentTypeInclude.inc"%>
<%@include file = "emxNavigatorBaseInclude.inc"%>
