<?xml version="1.0" ?>
<ProcedurePackage 
	xmlns="PLMDictionaryProcedure"
	Name="DocumentCompletion_allRelationshipCompletion">
	
	<Procedure Name="DocumentCompletion_allRelationshipCompletion">
		<Implementation Name="DocumentCompletion_allRelationshipCompletion" FileLocation="DocumentCompletion_allRelationshipCompletion.KProc" Language="EKL"/>
		<Signature href="DocumentCompletion_allRelationshipCompletion_sign"/>
	</Procedure>
	
	<Signature id="DocumentCompletion_allRelationshipCompletion_sign">
		<Parameter Name="InputIds" Lower="0" Upper="-1" MultiValuated="Yes" Direction="in" DataType="PLMId"/>
		<Parameter Name="OutputIds" Lower="0" Upper="-1" MultiValuated="Yes" Direction="out" DataType="PLMId"/>
	</Signature>
		
</ProcedurePackage>
