<%--
  emxComponentTags.inc

  Defines tags for the Components suite.

  Copyright (c) 1992-2020 Dassault Systemes.

  All Rights Reserved.
  This program contains proprietary and trade secret information
  of MatrixOne, Inc.  Copyright notice is precautionary only and
  does not evidence any actual or intended publication of such program

  
--%>

<%@include file = "../emxTagLibInclude.inc"%>

<framework:localize id="i18nId" bundle="emxComponentsStringResource"
        locale='<%= request.getHeader("Accept-Language") %>'/>

