<%--
  emxProgramScripts.inc

  Defines Java Scripts for the Program Central suite.

  Copyright (c) 1992-2020 Dassault Systemes.

  All Rights Reserved.
  This program contains proprietary and trade secret information
  of MatrixOne, Inc.  Copyright notice is precautionary only and
  does not evidence any actual or intended publication of such program

  static const char RCSID[] = "$Id: emxProgramScripts.inc.rca 1.6 Wed Oct 22 15:49:14 2008 przemek Experimental przemek $"
--%>

<script language="javascript">
<!-- hide JavaScript from non-JavaScript browsers

  // Define translated variables required for emxProgramUtil.js.

  var confirmDeleteMessage = "<emxUtil:i18nScript localize="i18nId">emxProgramCentral.Common.ConfirmDelete</emxUtil:i18nScript>";
  var selectItemToDelete = "<emxUtil:i18nScript localize="i18nId">emxProgramCentral.Common.SelectItemToDelete</emxUtil:i18nScript>";
  var selectItem = "<emxUtil:i18nScript localize="i18nId">emxProgramCentral.Common.SelectItem</emxUtil:i18nScript>";
  var invalidActionForFunction = "<emxUtil:i18nScript localize="i18nId">emxProgramCentral.Common.InvalidActionForFunction</emxUtil:i18nScript>";
  var v4OrHigher = "<emxUtil:i18nScript localize="i18nId">emxProgramCentral.Common.V4OrHigher</emxUtil:i18nScript>";

// Stop hiding here -->
</script>

<script language="javascript" src="emxProgramUtil.js"></script>
<script language="javascript" src="modal.js"></script>
<script language="javascript" src="popups.js"></script>
