<%--  emxProgramStyle.inc   -  Top Level Include File for Program Central Suite

   Copyright (c) 1992-2020 Dassault Systemes.
   All Rights Reserved.
   This program contains proprietary and trade secret information of MatrixOne,
   Inc.  Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program

   static const char RCSID[] = "$Id: emxProgramStyle.inc.rca 1.8 Wed Oct 22 15:49:18 2008 przemek Experimental przemek $"
--%>
<style type="text/css">

A:link {
	 COLOR: #0000ff;FONT-SIZE: 12px
}
A:hover {
	COLOR: #0000ff;FONT-SIZE: 12px
}
A:active {
	COLOR: #0000ff;FONT-SIZE: 12px
}
A:visited {
	COLOR: #0000ff;FONT-SIZE: 12px
}
A.indent:link {
	COLOR: #336699; FONT-SIZE: 12px; font-weight:bold ;text-decoration:none
}
A.indent:hover {
	COLOR: #336699; FONT-SIZE: 12px; font-weight:bold ;text-decoration:none
}
A.indent:active {
	COLOR: #336699; FONT-SIZE: 12px; font-weight:bold ;text-decoration:none
}
A.indent:visited {
	COLOR: #336699; FONT-SIZE: 12px; font-weight:bold ;text-decoration:none
}

BODY {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px; FONT-WEIGHT: normal
}
P {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px; FONT-WEIGHT: normal
}
TD {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px; FONT-WEIGHT: normal
}
TD.small
  {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 10px; FONT-WEIGHT: normal
  }
TD.tdsmall
  {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 10px; FONT-WEIGHT: normal
  }
TD.smallBold
  {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 10px; FONT-WEIGHT: bold
  }
TD.medBold
  {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 11px; FONT-WEIGHT: bold
  }
TD.norBold
  {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px; FONT-WEIGHT: bold
  }
TH {
	text-align:left
}
H1 {
	FONT-SIZE: 23px; FONT-WEIGHT: bold
}
H2 {
	FONT-SIZE: 19px; FONT-WEIGHT: bold
}
H3 {
	FONT-SIZE: 15px; FONT-WEIGHT: bold
}
H4 {
	FONT-SIZE: 12px; FONT-WEIGHT: bold
}
B {
	FONT-WEIGHT: bold
}
STRONG {
	FONT-WEIGHT: bold
}
I {
	FONT-STYLE: italic
}
EM {
	FONT-STYLE: italic
}
INPUT {
	COLOR: #000088; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px
}
TEXTAREA {
	COLOR: #000088; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px
}

.normal {
	COLOR: #000000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px
}
.legal {
	COLOR: #808080; FONT-SIZE: 12px
}
.copyright {
	COLOR: #808080; FONT-SIZE: 10px
}
.small {
	FONT-SIZE: 11px;BACKGROUND-COLOR:#ffffff
}
.xsmall {
	FONT-SIZE: 9px ;color:#9d9d9d
}
.smallv {
	FONT-FAMILY: verdana, arial; FONT-SIZE: 10px
}
.smallpress {
	COLOR: #330099; FONT-SIZE: 10px
}

.newstable {
	BACKGROUND-COLOR: #ffffff; FONT-SIZE: 10px
}
.lighttext {
	COLOR: #ffffff; FONT-SIZE: 12px ;font-weight:bold
}
.heading {
	COLOR: #000080; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px
}
.altheading {
	BACKGROUND-COLOR:white;COLOR: #000080; FONT-FAMILY: arial, helvetica; FONT-SIZE: 14px;font-weight:bold
}
.activerow {
	BACKGROUND-COLOR:#18345a;COLOR: #ffffff; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px
}

.thheading {
	BACKGROUND-COLOR: #336699; color:white; FONT-FAMILY: Arial, helvetica; FONT-SIZE: 12px ; font-weight:bold;
}

.centerheading {
	BACKGROUND-COLOR:#336699;color:white; FONT-FAMILY: arial, helvetica; FONT-SIZE: 12px ;font-weight:bold;text-align:center
}
.thheadingsm {
	BACKGROUND-COLOR:#336699;color:white; FONT-FAMILY: arial, helvetica; FONT-SIZE: 10px ;font-weight:bold;
}
.dark {
	BACKGROUND-COLOR: #18345a;
}
.light {
	BACKGROUND-COLOR: #336699;
}
.white {
	BACKGROUND-COLOR: #ffffff;
}

A.tab:link {
		COLOR: #ffffff; FONT-SIZE: 12px; FONT-FAMILY: arial,verdana;TEXT-DECORATION: none;font-weight:bold
}
A.tab:hover {
			COLOR: #ffffff; FONT-SIZE: 12px; FONT-FAMILY: arial,verdana;TEXT-DECORATION: none;font-weight:bold
}
A.tab:active {
			COLOR: #ffffff; FONT-SIZE: 12px; FONT-FAMILY: arial,verdana;TEXT-DECORATION: none;font-weight:bold
}
A.tab:visited {
		COLOR: #ffffff; FONT-SIZE: 12px; FONT-FAMILY: arial,verdana;TEXT-DECORATION: none;font-weight:bold
}
A.altheadinglink:link {
	COLOR: #ff0000; FONT-FAMILY: arial, helvetica; FONT-SIZE: 14px;font-weight:bold ;text-decoration:none
}
A.altheadinglink:hover {
	COLOR: #0000ff; FONT-FAMILY: arial, helvetica; FONT-SIZE: 14px;font-weight:bold ;text-decoration:none
}
A.altheadinglink:active {
	COLOR: #0000ff; FONT-FAMILY: arial, helvetica; FONT-SIZE: 14px;font-weight:bold ;text-decoration:none
}
A.altheadinglink:visited {
	COLOR: #0000ff; FONT-FAMILY: arial, helvetica; FONT-SIZE: 14px;font-weight:bold ;text-decoration:none
}

table.border { background-color: #003366 }
TH { color: #FFFFFF; font-weight: bold; font-size: 12px; font-family: Verdana, Arial, Helvetica, Geneva, Swiss, SunSans-Regular; background-color: #609BC0 }


TR.odd {
   color:#13345a;background-color:#dbdbdb
}
TR.even {
   color:#13345a;background-color:#ffffff
}
TD.oddsm {
   color:#13345a;background-color:#dbdbdb; FONT-SIZE: 10px
}
TD.evensm {
   color:#13345a;background-color:#ffffff; FONT-SIZE: 10px
}

TD.pageHeader {
    font-weight: bold; font-size: 14px;
	font-family : Verdana, Geneva, Arial, Helvetica, sans-serif;
	color : Maroon;
}
<%-- ITI: grayedOut and selected added for Task dependencies --%>
TD.grayedOut {
    font-weight: bold; font-size: 10px;
	font-family : Verdana, Geneva, Arial, Helvetica, sans-serif;
	color : Gray;
}
TD.completed {
    font-weight: bold; font-size: 10px;
	font-family : Verdana, Geneva, Arial, Helvetica, sans-serif;
	color : Green;
}
TD.selected {
    font-weight: bold; font-size: 12px;
	font-family : Verdana, Geneva, Arial, Helvetica, sans-serif;
	color : Red;
}
<%-- kds
td.label { color: #333333; font-size: 12px; font-weight: bold;  background-color: #CCCCCC }
--%>
td.labeltext { color: #333333; font-weight: bold }
td.headline { color: #FFFFFF; font-weight: bold; font-size: 16px; font-family: Verdana, Arial, Helvetica, Geneva, SunSans-Regular }
td.fieldback { background-color: #DDDDDD }
<%-- kds
td.field { color:#13345a;background-color:#dbdbdb; FONT-SIZE: 12px}
--%>
td.whitetext { color: #FFFFFF; font-weight: bold; font-size: 12px}


.blue {text-decoration:none;background-color:#18345a}
.backblue {color:white;background-color:#33659c}
.diva {position:absolute}
.divr {position:relative}
.mid {text-align:center;vertical-align:middle}

.odd {color:#13345a;background-color:#dbdbdb }

.even { color:#13345a;background-color:#ffffff }



body.searchTree { background-color: #dedede; }
body.searchTree a { color: #18345a; }
body.searchTree font { font-size: 9pt; font-family: Arial, Helvetica, Sans-Serif; }
body.searchTree font.root { font-weight: bold; }



/* --------------------------------------------------------------------
// Page Header Settings
// -------------------------------------------------------------------- */

/* Page Header Text Appearance */
td.pageHeader {  font-family: Arial, Helvetica, Sans-Serif; font-size: 13pt; font-weight: bold; color: #990000; }

/* Page Header Border Appearance */
td.pageBorder {  background-color: #003366; }

/* ====================================================================
// Form Stylesheet
// by Nicholas C. Zakas
// ==================================================================== */


/* Default Label Appearance */
td.label { background-color: #dddecb; color: black; font-weight: bold; height: 24px; }

/* Required Label Appearance */
td.labelRequired { background-color: #dddecb; color: #990000; font-weight: bold; height: 24px; ; font-style: italic }

/* Display Field Appearance */
td.field { background-color: #eeeeee; }

/* Input Field Appearance */
td.inputField { background-color: #eeeeee; font-size: 12px; }

/* Required Notice Appearance */
td.requiredNotice {  font-family: Arial, Helvetica, sans-serif; color: #990000}

/* ====================================================================
// Stylesheet additions
// -Paul Petty-
// ==================================================================== */

td.bold { color: black; font-weight: bold }
td.italics { color: black; font-style: italic }
td.noresult   { color: #ff0000; font-style: italic; font-weight: bold; background-color: #ffffff; text-align: center }
table.symbolborder { background-color: #999999 }
table.symbolback { font-weight: bold; background-color: #EEEEEE}

</style>

