<%--
  emxProgramGuiPageBorder.inc -- This inserts a page border in the calling jsp.

  Copyright (c) 1992-2020 Dassault Systemes.

  All Rights Reserved.
  This program contains proprietary and trade secret information
  of MatrixOne, Inc.  Copyright notice is precautionary only and
  does not evidence any actual or intended publication of such program

   static const char RCSID[] = "$Id: emxProgramGuiPageBorder.inc.rca 1.5 Wed Oct 22 15:49:42 2008 przemek Experimental przemek $"

  Usage: <%@ include file="emxProgramGuiPageBorder.inc" %>
--%>

  <table border="0" cellspacing="0" cellpadding="0" width="100%">
    <tr> 
      <td class="pageBorder"><img src="images/spacer.gif" width="1" height="1" /></td>
    </tr>
  </table>

