<%--
  emxProgramTags.inc

  Defines tags for the Program Central suite.

  Copyright (c) 1992-2020 Dassault Systemes.

  All Rights Reserved.
  This program contains proprietary and trade secret information
  of MatrixOne, Inc.  Copyright notice is precautionary only and
  does not evidence any actual or intended publication of such program

  static const char RCSID[] = "$Id: emxProgramTags.inc.rca 1.7 Wed Oct 22 15:49:13 2008 przemek Experimental przemek $"
--%>

<%@include file = "../emxTagLibInclude.inc"%>

<framework:localize id="i18nId" bundle="emxProgramCentralStringResource"
        locale='<%= request.getHeader("Accept-Language") %>'/>

