<%--
  emxprojectDashboardsUtil.inc

  Bottom Include File for all jsp Dashboard pages

  Copyright (c) 1992-2020 Dassault Systemes.

  All Rights Reserved.
  This program contains proprietary and trade secret information
  of MatrixOne, Inc.  Copyright notice is precautionary only and
  does not evidence any actual or intended publication of such program

  static const char RCSID[] = "$Id: emxprojectDashboardsUtil.inc.rca 1.14 Wed Oct 22 15:49:42 2008 przemek Experimental przemek $"
--%>
