<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title>UI Manager</title>
        <meta http-equiv="Content-Type"    content="text/html; charset=windows-1252" />

        <link rel="stylesheet" type="text/css"    href="assets/ext/3.2.1/resources/css/ext-all.css" />
        <link rel="stylesheet" href="assets/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css"    href="assets/ext/3.2.1/resources/css/custom.css" />
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="assets/app.css" />

        <script type="text/javascript"    src="assets/ext/3.2.1/adapter/ext/ext-base-debug.js"></script>
        <script type="text/javascript" src="assets/ext/3.2.1/ext-all-debug.js"></script>

        <link rel="stylesheet" type="text/css"    href="assets/ext/3.2.1/ux/css/RowEditor.css" />
        <script type="text/javascript" src="assets/ext/3.2.1/ux/RowEditor.js"></script>

        <link rel="stylesheet" href="assets/ext/3.2.1/ux/fileuploadfield/css/fileuploadfield.css" />
        <script type="text/javascript" src="assets/ext/3.2.1/ux/fileuploadfield/FileUploadField.js"></script>

        <script type="text/javascript">
            var dsCsrfOptions = $csrfOptions$;
        </script>
        <script type="text/javascript" src="assets/app.js"></script>
    </head>
    <body>
        <div id="global"></div>
    </body>
</html>
