<%--  emxTeamDocUtil.jsp   - utility functions for TeamCentral Document files
   Copyright (c) 1992-2020 Dassault Systemes.
   All Rights Reserved.
   This program contains proprietary and trade secret information of MatrixOne,
   Inc.  Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program

   static const char RCSID[] = $Id: emxTeamDocUtil.inc.rca 1.14 Wed Oct 22 16:05:54 2008 przemek Experimental przemek $
--%>
<%@ page import="com.matrixone.apps.domain.*, matrix.db.*, matrix.util.*, com.matrixone.servlet.*, java.util.*, com.matrixone.apps.framework.taglib.*, com.matrixone.apps.domain.util.*"  %>
<%!
  static final StringList EMPTY_STRING_LIST_DOCUMENT_UTIL = new StringList(0).unmodifiableCopy();
%>
