<%--  DSCContentTypeInclude.inc

   Copyright (c) 2016-2020 Dassault Systemes. All rights reserved.
   This program contains proprietary and trade secret information of
   Dassault Systemes and its subsidiaries. Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program

--%>
<%--



   static const char RCSID[] = $Id: /ENODesignerCentral/CNext/webroot/integrations/DSCContentTypeInclude.inc 1.3 Sat Apr 26 10:22:24 2008 GMT ds-mbalakrishnan Experimental$
--%>

<%@page contentType="text/html; charset=UTF-8"%>
