<?xml version="1.0" ?>
<ProcedurePackage 
	xmlns="PLMDictionaryProcedure"
	Name="DocumentCompletion_allDocumentCompletion">
	
	<Procedure Name="DocumentCompletion_allDocumentCompletion">
		<Implementation Name="DocumentCompletion_allDocumentCompletion" FileLocation="DocumentCompletion_allDocumentCompletion.KProc" Language="EKL"/>
		<Signature href="DocumentCompletion_allDocumentCompletion_sign"/>
	</Procedure>
	
	<Signature id="DocumentCompletion_allDocumentCompletion_sign">
		<Parameter Name="InputIds" Lower="0" Upper="-1" MultiValuated="Yes" Direction="in" DataType="PLMId"/>
		<Parameter Name="OutputIds" Lower="0" Upper="-1" MultiValuated="Yes" Direction="out" DataType="PLMId"/>
	</Signature>
		
</ProcedurePackage>
