<?xml version="1.0" ?>
<ProcedurePackage 
	xmlns="PLMDictionaryProcedure"
	Name="ManufacturerEquivalentItemCompletion">
	
	<Procedure Name="ManufacturerEquivalentItemCompletion">
		<Implementation Name="ManufacturerEquivalentItemCompletion" FileLocation="ManufacturerEquivalentItemCompletion.KProc" Language="EKL"/>
		<Signature href="ManufacturerEquivalentItemCompletion_sign"/>
	</Procedure>
	
	<Signature id="ManufacturerEquivalentItemCompletion_sign">
		<Parameter Name="InputIds" Lower="0" Upper="-1" MultiValuated="Yes" Direction="in" DataType="PLMId"/>
		<Parameter Name="OutputIds" Lower="0" Upper="-1" MultiValuated="Yes" Direction="out" DataType="PLMId"/>
	</Signature>
		
</ProcedurePackage>
